

** 核心人物

- 1706-1790 富兰克林 本杰明·富兰克林（英语：Benjamin Franklin，1706年1月17日－1790年4月17日）
- 1736-1806 库仑 查利·奥古斯丁·库仑（Charles-Augustin de Coulomb，1736年6月14日—1806年8月23日）
- 1745-1827 伏特 亚历山德罗·朱塞佩·安东尼奥·安纳塔西欧·伏特（Count Alessandro Giuseppe Antonio Anastasio Volta，1745年2月18日－1827年3月5日）
- 1775-1836 安培 安德烈·玛丽·安培（André-Marie Ampère，1775年1月20日 — 1836年6月10日）
- 1777-1851 奥斯特 汉斯·克海斯提安·奥斯特（丹麦语：Hans Christian Ørsted，1777年8月14日－1851年3月9日）
- 1791-1867 法拉第 迈克尔·法拉第 （Michael Faraday，1791年9月22日～1867年8月25日）
- 1831-1879 麦克斯韦 詹姆斯·克拉克·麦克斯韦（James Clerk Maxwell，1831年6月13日—1879年11月5日）
- 1834-1907 门捷列夫 德米特里·伊万诺维奇·门捷列夫（俄语：Дмитрий Иванович Менделеев，1834年2月7日—1907年2月2日）
- 1853-1928 洛伦兹 亨德里克·安东·洛伦兹（Hendrik Antoon Lorentz，1853年7月18日-1928年2月4日）
- 1856-1943 特斯拉 尼古拉·特斯拉（英语：Nikola Tesla，1856年7月10日－1943年1月7日）
- 1857-1894 赫兹 海因里希·鲁道夫·赫兹（Heinrich Rudolf Hertz，1857年2月22日－1894年1月1日）
- 1856-1940 汤姆逊 约瑟夫·约翰·汤姆逊（Joseph John Thomson，1856年12月18日——1940年8月30日）
- 1858-1947 普朗克 马克斯·普朗克（全名：马克斯·卡尔·恩斯特·路德维希·普朗克，Max Karl Ernst Ludwig Planck，1858年4月23日—1947年10月4日）
- 1871-1937 卢瑟福 欧内斯特·卢瑟福（Ernest Rutherford，1871年8月30日—1937年10月19日）

** 原子史

*** 时间线
- 早在两千四百年前，古希腊著名的哲学家德谟克里特提出了“原子”的概念，认为自然界的一切物质都是由一些坚硬不可分的小颗粒构成，并命“小微粒”为原子。
- 1661年，英国化学家波义耳提出物质组成的元素说开始建立
- 1803年，道尔顿原子模型：原子是组成物质的基本的粒子，它们是坚实的、不可再分的实心球。
- 1811年，阿佛加德罗提出分子概念
- 1860年，国际化学会议，分子概念得到认可
- 1869年，俄国化学家门捷列夫找到了物质之间相互变化的内在联系和规律，发现了著名的化学元素周期律
- 1879年，克鲁克斯研究气体放电管中气体的放电现象
- 1897年，汤姆逊发明 "电子" 以来的微观世界结构的理论是不对的
- 1900年，普朗克首次提出了能量量子化，标志着量子论诞生 e=hv
- 1904年，汤姆生原子模型：原子是一个平均分布着正电荷的粒子，其中镶嵌着许多电子，中和了正电荷，从而形成了中性原子。
- 1911年，卢瑟福原子模型：在原子的中心有一个带正电荷的核，它的质量几乎等于原子的全部质量，电子在它的周围沿着不同的轨道运转，就像行星环绕太阳运转一样。
- 1913年，玻尔原子模型：电子在原子核外空间的一定轨道上绕核做高速的圆周运动。
- 1916年，德国化学家柯赛尔和美国化学家路易斯创立了经典的电价理论和共价理论
- 1919年，卢瑟福用人为的方法第一次分裂了原子，他用a粒子轰击氮原子，使它变成了一个氧原子和一个氢原子。
- 1926年，卢瑟福特设计出了一架巨型原子捣碎机，用这架仪器，他们把轻金属锂转变为氦。
- 1933年，卢瑟福发现和命名了质子——氢原子核，并预言核内存在着中子。

*** 1803 道尔顿原子模型

1803年10月，在曼彻斯特文学和哲学学会的一次活动中，道尔顿第一次讲述了他的原子论。他的基本观点可归纳为三点:

(1)元素是由非常微小、不可再分的微粒——原子组成，原子在一切化学变化中不可再分，并保持自己的独特性质。

(2)同一元素所有原子的质量、性质都完全相同。不同元素的原子质量和性质也各不相同，原子质量是每一种元素的基本特征之一。

(3)不同元素化合时，原子以简单整数比结合。

*** 1811 分子 阿佛加德罗常数

1811年他写了一篇论文，在文中他首先声明自己的观点来源于盖·吕萨克的气体实验事实，接着他明确地提出了分子的概念，认为单质或化合物在游离状态下能独立存在的最小质点称作分子，单质分子由多个原子组成，他修正了盖·吕萨克的假说，提出：“在同温同压下，相同体积的不同气体具有相同数目的分子。”“原子”改为“分子”的一字之改，正是阿佛加德罗假说的奇妙之处。由此可见，对科学概念的理解必须一丝不苟。对此他解释说，之所以引进分子的概念是因为道尔顿的原子概念与实验事实发生了矛盾，必须用新的假说来解决这一矛盾。这就是1811年阿佛加德罗提出分子假说的主要内容和基本观点。

直到他1856年逝世，分子假说仍然没有被大多数化学家所承认。道尔顿的原子论发表后，测定各元素的原子量成为化学家最热门的课题。尽管采用了多种方法，但因为不承认分子的存在，化合物的原子组成难以确定，原子量的测定和数据呈现一片混乱，难以统一。1860年9月在德国卡尔斯鲁厄召开了国际化学会议，分子概念得到认可。

在验证中，人们证实在温度、压强都相同的情况下，1摩尔的任何气体所占的体积都相等。例如在0℃、压强为760mmHg时，1摩尔任何气体的体积都接近于22．4升，人们由此换算出：1摩尔任何物质都含有6．02205×1023个分子，这一常数被人们命名为阿佛加德罗常数，以纪念这位杰出的科学家。

*** 1897 电子

1879年，克鲁克斯研究气体放电管中气体的放电现象，当放电管中的气压降低到0.01MM汞柱时，在放电管中通上高压，在正对阴极的玻璃壁上就会发出荧光。实验证明，荧光是由于阴极所发射的一股射线激发玻璃壁中的原子而产生的。这股射线还能推动安放在放电管中的云母风车转动，证明这种射线是一股粒子流。这种射线在行进过程中，磁场或电场都能使它偏转方向，就证明了这股射线带电。由于这股射线是从阴极产生的，因此，科学家就把这种带电的粒子流叫做阴极射线；这种高真空的放电管则称为阴极射线管。物理学家用各种各样的说法来阐明阴极射线的本质，例如，克鲁克斯认为它是“物质的第四态”或“超气态物质”。

1897年著名的英国物理学家汤姆生则认为阴极射线是一种带负电的微粒子，并且用实验证明了电子的存在。有力地证明原子是不可再分的最小微粒的错误结论。

*** 1900 普朗克辐射公式

1896年，马克斯·普朗克开始对热辐射进行了系统的研究。期间为了解决瑞利-金斯公式只在低频范围符合，而维恩公式（维恩位移定律）只在高频范围符合，1899年，马克斯·普朗克提出了“基础无序原理”（principle of elementary disorder），并把瑞利-金斯定律和维恩位移定律这两条定律使用一种熵列式进行内插，可以很好地描述测量结果

1900年10月下旬，马克斯·普朗克在《德国物理学会通报》上发表一篇只有三页纸的论文，题目是《论维恩光谱方程的完善》，第一次提出了黑体辐射公式。12月14日，在德国物理学会的例会上，他作了《论正常光谱中的能量分布》的报告，在报告中指出，为了从理论上得出正确的辐射公式，必须假定物质辐射（或吸收）的能量不是连续地、而是一份一份地进行的，只能取某个最小数值的整数倍，这个最小数值就叫能量子，能量的最小数值表示为：

e=hv

该公式称为普朗克辐射公式或普朗克定律，其中，ν是辐射频率，h被马克斯·普朗克叫做基本作用量子，后来被命名为普朗克常数。

普朗克常数 = 6.626068 * 10^-34 J.s

*** 1904 汤姆生原子模型

汤姆生在发现电子以后，又于1904年提出了一种原子模型，认为原子是一个平均分布着正电荷的粒子，其中镶嵌着许多电子，中和了正电荷，从而形成了中性原子。

*** 1911年 卢瑟福原子模型

卢瑟福终于设计出了一个试验装置：一个“A”射线的放射源，就像一挺机关枪，一个金属箔作靶子，就像放核桃的草地，在它的旁边放一个硫化锌的荧光屏，屏后安装一架显微镜，来观察实验的情况。

在原子的中心有一个带正电荷的核，它的质量几乎等于原子的全部质量，电子在它的周围沿着不同的轨道运转，就像行星环绕太阳运转一样。

*** 1912 同位素

1912年，汤姆生利用磁场的作用测量了带正电的气体离子(称为极隧射线)的荷质比，发现在磁分离器中，相同荷质比的粒子在荧光屏上形成一束抛物线。在这些气体离子的抛物线中，除了质量为20单位的氖的抛物线外，还有一条质量为22单位的抛物线，从而发现了质量为22单位的氖的稳定同位素，这是世界上第一次发现的稳定同位素。汤姆生的学生阿斯顿将天然的氖进行扩散分离，最后得到两部分氖气，它们的相对分子质量分别为20.15和21.56，证实了氖－22的存在。

*** 1913 玻尔原子模型

玻尔的原子理论给出这样的原子图像：
1.电子在一些特定的可能轨道上绕核作圆周运动，离核愈远能量愈高；
2.可能的轨道由电子的角动量必须是 h/2π的整数倍决定；
3.当电子在这些可能的轨道上运动时原子不发射也不吸收能量，只有当电子从一个轨道跃迁到另一个轨道时原子才发射或吸收能量，而且发射或吸收的辐射是单频的，辐射的频率和能量之间关系由 E=hv给出。

h为普朗克常数。h=6.626×10^(-34)J·s

玻尔的理论成功地说明了原子的稳定性和氢原子光谱线规律。

*** 1933 质子

质子(proton)是一种带1.6 × 10-19库仑(C)正电荷的亚原子粒子，直径约1.6~1.7×10−15m，质量是938百万电子伏特/c²(MeV/c²)，即1.672621637（83）×10-27千克，大约是电子质量的1836.5倍（电子的质量为9.10938215（45）×10-31千克），质子比中子稍轻（中子的质量为1.674927211（84）×10-27千克）。

1918年他任卡文迪许实验室主任时，用α粒子轰击氮原子核，注意到在使用α粒子轰击氮气时他的闪光探测器纪录到氢核的迹象。

质子命名为proton，这个单词是由希腊文中的“第一”演化而来的。卢瑟福认识到这些氢核唯一可能的来源是氮原子，因此氮原子必须含有氢核。他因此建议原子序数为1的氢原子核是一个基本粒子。

1919年，卢瑟福做了用α粒子轰击氮原子核的实验，实验装置如图所示，容器C里放有放射性物质A，从A射出的α粒子射到铝箔F上，适当选取铝箔的厚度，使容器C抽成真空后，α粒子恰好被F吸收而不能透过，在F后面放一荧光屏S，用显微镜册来观察荧光屏上是否出现闪光．通过阀门T往C里通进氮气后，卢瑟福从荧光屏S上观察到了闪光，把氮气换成氧气或二氧化碳，又观察不到闪光，这表明闪光一定是α粒子击中氮核后产生的新粒子透过铝箔引起的。

卢瑟福把这种粒子引进电场和磁场中，根据它在电场和磁场中的偏转，测出了它的质量和电量，确定它就是氢原子核，又叫做质子，通常用符号p表示。

后来，人们用同样的方法使氟、钠、铝等核发生了类似的转变，并且都产生了质子。由于各种核里都能轰击出质子，可见质子是原子核的组成部分。

水中的氢离子绝大多数都是水合质子。质子在化学和生物化学中起非常大的作用，根据酸碱质子理论，可以在水溶液中提供质子的物质一般被称为酸，可以在水溶液中吸收质子的物质一般被称为碱。

*** 1932 中子

中子是不带电的基本粒子，静止质量为1.6748×10-27kg，它的半径约为0.8×10-15m，与质子大小类似。中子常用符号n表示。中子的自旋量子数为1/2。

单独存在的中子是不稳定的，平均寿命约为16分，它将衰变成质子、电子和反中微子。原子核由中子和质子组成，原子核内的中子是稳定的。由于中子不带电，所以容易打进原子核内，引起各种核反应。

1932年英国物理学家查德威克在用α粒子轰击铍的实验中发现了中子。

** 电磁史

*** 时间线
人类认识电现象和磁现象是相当早的

- 1600年，吉尔伯特的研究首先区分了电现象和磁现象
- 1660年，格里克基于摩擦起电现象研制成功摩擦起电机
- 1720年，英国格雷发现了电的传导现象并对其深入研究后提出了导体和绝缘体的概念，还发现了导体的静电感应现象。
- 1733年，杜菲通过实验认为自然界存在两种电荷，电的双流体理论
- 1745年，穆欣布洛克和克莱斯特分别独立发明了能够储存静电的莱顿瓶
- 1750年，富兰克林提出正负电荷，电荷守恒思想，避雷针，电的单流体理论
- 1754年，英国康顿用“电的单流体理论”解释了静电感应现象，静电力基本特性、电荷守恒和静电感应原理都已建立
- 1785年，库仑（C.A.Coulomb 1736-1806）发现了静态-电荷间的作用力与距离平方成反比的定律，奠定了静电的基本定律。
- 1799年，意大利的伏特（A.Voult）用铜片和锌片浸于食盐水中，并接上导线，制成了第一个电池，他提供首次的连续性的电源，堪称现代电池的元祖。
- 1820年，丹麦奥斯特发现电生磁现象
- 1820年，法国安培提出用来判定电流磁场方向的右手螺旋定则
- 1826年，欧姆发现了欧姆定律。
- 1829年，亨利发现了自感现象并独立于法拉第发现了互感现象。他还发明了电铃和电磁继电器
- 1831年，英国法拉第（M. Faraday），磁生电，利用磁场效应的变化，展示感应电流的产生。制出了世界上最早的第一台发电机。
- 1832年，法国人毕克西发明了手摇式直流发电机。
- 1833年，德国数学家高斯和青年电学家韦伯在哥丁根建立了一个电报系统
- 1837年，莫尔斯发明了一套用点、划组成的著名的“莫尔斯电码”。
- 1865年，苏格兰的麦克斯韦提出电磁场理论的数学式，预测了电磁波辐射的传播存在。将电学与磁学统合成一种理论，同时证明了光是电磁波的一种。
- 1866年，德国人西门子（Siemens）制成世界上第一台工业用发电机，自励式直流发电机。
- 1876年，美国的贝尔首先发明了电话。
- 1876年，爱迪生发明了留声机。
- 1879年，爱迪生发明电灯
- 1882年，美国的戈登制造出了输出功率447KW，高3米，重22吨的两相式巨型发电机；
- 1888年，德国赫兹（H.Hertz）验证电磁波的存在
- 1895年，洛伦兹（H.A.Lorentz）假设分裂性的电荷是电子（electron）。
- 1895年，意大利物理学家马可尼又发明了无线电报。
- 1896年，特斯拉的两相交流发电机在尼亚拉发电厂开始劳动营运，3750KW，5000V的交流电一直送到40公里外的布法罗市；
- 1897年，英国汤姆生（J.J.Thomson）证实电子的电性是带负电性。
- 1898年，由伟恩（W.Wien）在观察阳极射线的偏转中发现带正电粒子的存在。
- 1889年，西屋公司在俄勒冈州建设了发电厂，1892年成功地将15000伏电压送到了皮茨菲尔德。
- 1892年，洛伦兹建立经典电子论，给出了电子在磁场中受力的描述，现今称为洛伦兹力。
- 1906年，爱迪生用钨丝来做灯泡，一直沿用到今天。

*** 磁

公元前6世纪，古希腊古风时期的学者泰勒斯最早以成文方式记述了磁石能够吸铁、经过摩擦后的琥珀能够吸引轻小物体等现象。由于古希腊人发现磁石的地方叫做Magnesia，就把这种石头称为Magnes lithos，后来逐渐转化为拉丁语词magnetum 及英语词magnet并用于表达“磁”这一含义。

*** 1600 电

1600年，吉尔伯特的研究首先区分了电现象和磁现象，提出磁石上的正、负极（即现代术语所指的N、S极）必定成对出现而不会独立存在，发现了电现象在水中消失但磁现象仍存在，发现磁力在高温下消失等现象。他的著作《De Magnete》[3]提出了地球是一个巨大磁体的假说和星球间引力源于磁性的假说（这时人类还尚未科学地认识万有引力）。

在这一著作中，吉尔伯特根据“琥珀”一词的希腊语词elektron、古拉丁语词electrum创造了拉丁语词electricus以表达“电”这一含义，后来转化为英语词electric并沿用至今。为了纪念他，在曾经广泛应用的CGS单位制中磁动势的单位就是吉伯（符号为Gb或Gi）。

*** 1733 电的双流体理论

1733年，杜菲通过实验认为自然界存在两种电荷并将其分别命名为“vitreous”（原意为玻璃）和“resinous”（原意为松脂），指出电荷间相互作用表现为同种电荷相互排斥、异种电荷相互吸引的基本特征，被称为“电的双流体理论”。

*** 1745 莱顿瓶

1745--1746年间，穆欣布洛克和克莱斯特（Ewald Georg von Kleist，1700--1748，德国物理学家、法学家）分别独立发明了能够储存静电的莱顿瓶，静电学研究从此有了廉价易得、使用方便的静电来源。莱顿瓶的结构成为现代电容器的先声。

典型的莱顿瓶是一个玻璃容器，内外包覆着导电金属箔作为极板。瓶口上端接一个球形电极，下端利用导体（通常是金属锁链）与内侧金属箔或是水连接。莱顿瓶的充电方式是将电极接上静电产生器或起电盘等来源，外部金属箔接地；内部与外部的金属将会携带相等但极性相反的电荷。

*** 1750 电的单流体理论

1750年，富兰克林通过实验认为电现象是一种分布在所有物体内的、没有质量的流体（他将之称为“电流体”）所产生的作用（这一观点显然受到了以太论的影响）：当物体所含的电流体为其自然拥有的数量时，称物体处于“电中性”，当物体所含的电流体大于其自然拥有的数量时，称物体“带正电”，反之则称物体“带负电”。富兰克林认为杜菲提出的“vitreous”对应了“带正电”、“resinous”对应了“带负电”（这一观点显然是人为规定的，但一直被沿用，使得后来发现的电子“带负电”而原子核“带正电”），这被称为“电的单流体理论”。

富兰克林还基于实验现象提出了电荷守恒思想，他认为在封闭系统中电流体的总量是不变的，它只能被重新分配而不能被创造，这使得将数学工具引入电现象的研究成为可能。他的另一个重大贡献是发明了避雷针，这标志着人类第一次驯服了“天电”，有效解决了高大建筑物被雷击的问题，人类对雷电防护技术的研究由此发端。

*** 1785 库仑定律

1785年，库仑通过著名的“扭秤实验”总结出了电荷之间相互作用的基本规律，即现在所称的库仑定律，这是静电学得以建立的基本实验定律。

*** 1799 铜锌电池
*** 1820 电生磁
*** 1820 安培 右手螺旋定则

对于直线电流，判定的方法是，用右手握住导线，让伸直的大拇指指向电流方向，那么，弯曲的四指所指的方向就是磁力线的环绕方向。对于通电的螺线管，判定的方法是，右手握住螺线管，让弯曲的四指指向环形电流方向，那么，伸直的大拇指所指的方向就是磁力线方向。


1821年，安培探索了磁现象的本质。他认为物体中的每个分子都有圆形电流，即分子电流，分子电流产生磁场，使每个分子都成为一个小磁体。当物体内部的分子电流杂乱无章地排列时，它们的磁性相互抵消，而使物体不显示磁性；当物体内部的分子电流取向一致时，至少是部分地一致时，就使物体显示出磁性。这样，安培初步揭示了电和磁的内在联系，他的观点和现代观点非常接近。

后人为了纪念他，把电流强度的单位命名为“安培”，简称“安”。

*** 1826 欧姆定律

1826年，欧姆发现了欧姆定律。部分电路的欧姆定律是：导体中的电流强度，跟这段导体两端的电压成正比，跟这段导体的电阻成反比。

全电路的欧姆定律是：电路中的电流强度跟电源的电动势成正比，跟整个电路的电阻（外电路电阻和电源电阻）成反比。

为了纪念欧姆，后人将电阻的单位命名为“欧姆”，简称为“欧”。

*** 1831 法拉第 磁生电 电磁感应定律

法拉第电磁感应定律：电路中感生电动势的大小，跟穿过这一电路的磁通量的变化成正比。这一发现成为现代电工学的基础，用于发电、送电等技术。

1833年，法拉第在实验中得出两条电解定律，被称为法拉第电解定律。

法拉第第一电解定律是：电解时，在电极上析出的物质的质量和通过电解液的电流强度及通电时间成正比。

法拉第第二电解定律是：一定量的电量所析出的物质的质量与该物质的化学当量成正比。

在发现电解定律的过程中，法拉第最先使用了电极、阳极、阴极、离于、阳离子、阴离子等名词。

1843年，法拉第第一个证明了电荷守恒定律，认为电荷既不能被创造，也不能被消灭。只能在物体内或在几个物体之间相互转移，电荷的代数和是守恒的。

法拉第还提出了电场、磁场、电力线、磁力线的概念，否定超距作用说，认为电力和磁力是通过电场和磁场传递的，并用电力线和磁力线直观描述电场和磁场。

1845年9月，法拉第在一次实验中发现了旋光效应，这就是著名的法拉第效应。在他用磁力线测试不同物体的磁效应时，发现透明固体和液体中的光的偏振面发生了旋转。对此，法拉第解释为“光线被磁化了”，这实际上是后来光的电磁说的萌芽。

上述成就是法拉第在各种自然力是统一的前提下长期探索的结果。

法拉第杰出的实验成就奠定了电磁学的基础，开创了电磁学研究的新时代。

*** 1865 麦克斯韦方程

麦克斯韦精心研究了法拉第的“力线”概念，在1855年发表了第一篇电磁学论文——《论法拉第的力线》。通过数学方法，他把电流周围存在磁力线的特征，概括为一个矢量微分方程，导出了法拉第的结论。

在研究电和磁的关系中，以前一直认为电流产生磁场，这个电流是指传导电流，法拉第也是这样认为的。麦克斯韦在实验中有了新的发现。

把两块中间夹着介质的金属板，也即是电容器，接在交变电源上，介质内并不存在自由电荷，也就是没有传导电流，但磁场却同样存在。

这个磁场是怎样产生的呢？麦克斯韦经过研究和分析，认为这里的磁场是由另一种类型的电流产生的，这种电流存在于任何电场变化的电介质中。他把这种电流称为“位移电流”，指出在位移电流的周围空间同样产生磁场，这种磁场和传导电流产生的磁场完全一样。

1862年，麦克斯韦发表了《论物理力线》的论文。这篇论文是他在电磁学理论方面的第二篇论文，已经不再是法拉第观点的数学翻译了，而是有了重大的引申和发展，首创了“位移电流”的新概念，指出不仅变化的磁场产生电场，而且变化的电场也产生磁场。

在这篇论文中，麦克斯韦还预见了电磁波的存在。在研究电场和磁场的交相变化过程时，他认识到这种相互变化的电磁场以波的形式向空间散布，由近及远。

他还对电磁学的定律进行了高度的概括，写出了数学方程，导出了电磁场的能量密度和电磁波的能量密度，指出电磁波就是能量的流动过程，从而说明了电磁波的物质性。

但是麦克斯韦并没有用实验来证实电磁波的存在。

1864年，麦克斯韦发表他的第三篇电磁学论文《电磁场的动力学理论》。在这篇论文里，麦克斯韦方程更完备了，它导出了电场与磁场的波动方程，其波的传播速度正好等于光的速度。这启发他提出了光的电磁学说，指出光也是一种电磁波，只不过是一种频率很低的电磁波，从而进一步认识了光的本质。

1873年，麦克斯韦出版了他的电磁学专著《电磁学通论》。

这部著作全面而系统地总结了电磁学研究的成果，成为电磁学的经典理论著作。这部著作的巨大意义，可与牛顿的《自然哲学数学原理》相媲美。如果说《自然哲学数学原理》是对经典力学的大综合，成为力学发展的里程碑，那么《电磁学通论》就是对电磁学的大综合，成为电磁学发展的里程碑。

在这部著作里，麦克斯韦以他特有的数学语言，建立了电磁学的微分方程组，揭示了电荷、电流、电场、磁场之间的普遍联系。这个电磁学方程，就是后来以他的名字著称的“麦克斯韦方程”。

麦克斯韦方程包括四个方面的内容：

1.法拉第感应定律；
2.描述电磁场对位移电流密度和传导电流密度的关系；
3.相当于库仑定律；
4.表明了除电源外，没有其他磁场源。

在《电磁学通论》中，电磁场、电磁波、光的电磁说都具有了严密的理论形态与数学模型，使电磁学发展到了高峰。

这样，一座宏伟的经典电磁学的理论大厦就由麦克斯韦建立起来了。

为了纪念他，人们把电磁单位制的磁通量单位定名为“麦克斯韦”。

*** 1888 赫兹 电磁波

1888年，赫兹终于发现了人们所怀疑的电磁波。

赫兹在两块正方形锌板的边缘中心，各接一根钢棒，然后使两根铜棒相隔一定距离并彼此绝缘而组成一个振荡器。在暗室中将电波环放置在距振荡器10米处。

实验时，将感应圈的高压电引至振荡器的两根铜棒上，使两铜棒间产生电火花，由此而辐射电磁波。

电波环的两个小球间闪现了电火花，这正是振荡器辐射的电磁波！

紧接着，赫兹进一步用实验证实了电磁波可以反射、折射、产生驻波，并测定了电磁波的传播速度。

赫兹在一间大而暗的教室墙上，安置了一块金属板。根据波动理论，如果电磁波能被反射，则反射波和人射波叠加应产生驻波。赫兹在金属板的对面放置有感应圈的振荡器，证实了振荡器发射的电磁波和金属板反射的电磁波叠加形成驻波。

赫兹还测定了电磁波的波长，计算出电磁波的传播速度，这个速度和光速的实验测定值非常接近，再次肯定了电磁波是以光速传播的。

他还用一块有孔的屏阻挡电波，使电波产生衍射；将电波通过一块大的沥青棱镜，证明电波像光波一样的折射，等等。

这些实验令人信服的地证明了电磁波是存在的，而且电磁波和光是统一的，有力地支持了麦克斯韦的电磁理论。

电磁波的发现对人类产生了巨大的影响。6年后，意大利的马可尼、俄国的波波夫实现了无线电传播，其他无线电技术如无线电报、无线电话、电视、雷达、卫星通信等等，像雨后春笋般涌现出来了。


